sudo: false
os:
 - linux
 - osx
language: d
d:
 - ldc
 - ldc-1.5.0
 - dmd
 - dmd-2.076.0
env:
 - ARCH="x86_64"
matrix:
  include:
    - {os: linux, d: ldc, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
script:
 - dub test --arch "$ARCH"
